title: Luke's Blog
description: "Luke's Blog and Portfolios"
author:
  name: "(Luke)Siyi Wei"
  email: "weisiyi2@gmail.com"
  url: "https://www.wei-siyi.com"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "Siyi Wei"
year : "2021"
