# Develop override settings

url: http://localhost:4000

analytics:
  provider: false

comments: true
  facebook:
    appid                : 475603466655907
    num_posts            : 5
    colorscheme          : "light"

sass:
  style: expanded